### ISSUE TITLE
Updates to web page

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/webpage#10]
Move some folks to alumni:

* Saur => PhD
* Headley => ugrad
* Toronto => postdoc
* Pina => PhD
* Rastogi => PhD
* Miller => PhD
* Mentzer => ugrad
* Jeon => PhD
* Mardziel => PhD
* Hammer => postdoc

Add some folks:

* Gilray => postdoc
* Vazou => postdoc
* Hietala => PhD
* Wyndham => PhD

(I hope I haven't missed anybody.)

**Comment by kmicinski** [comment]
Will do today.

**Comment by dvanhorn** [comment]
Thanks!

**Comment by kmicinski** [comment]
Done. Also moved Vu to alumni.

**Comment by dvanhorn** [comment]
Thanks!
